import { useState } from "react";
import { Send, Link as LinkIcon, Download, StickyNote } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import type { Relationship } from "@/features/matches/hooks/useUnifiedRelationships";
import { useMatchLocalState } from "./useMatchLocalState";
import { financialMetrics } from "./inboxHelpers";

export function ClientSharingCard({ rel }: { rel: Relationship }) {
  const { state, update } = useMatchLocalState(rel.matchId);
  const { toast } = useToast();
  const [shareOpen, setShareOpen] = useState(false);
  const [note, setNote] = useState(state.agentNote);

  const shareUrl = `${window.location.origin}/share/match/${rel.matchId}`;

  function confirmSend() {
    update({ sentToClientAt: new Date().toISOString() });
    setShareOpen(false);
    toast({ title: "Sent to client", description: rel.clientName ? `Notified ${rel.clientName}.` : undefined });
  }

  function copyLink() {
    navigator.clipboard.writeText(shareUrl).then(
      () => toast({ title: "Link copied" }),
      () => toast({ title: "Copy failed", variant: "destructive" }),
    );
  }

  function downloadOnePager() {
    const metrics = financialMetrics(rel);
    const lines = [
      `Property: ${rel.propertyName}`,
      `Location: ${[rel.propertyCity, rel.propertyState].filter(Boolean).join(", ") || "—"}`,
      `Match score: ${Math.round(rel.score)}/100`,
      "",
      "Financials",
      ...metrics.map((m) => `  ${m.label}: ${m.value}${m.estimated ? "  (est.)" : ""}`),
      "",
      "Generated by 1031ExchangeUp",
    ].join("\n");
    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${rel.propertyName.replace(/\s+/g, "_")}_one-pager.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "One-pager downloaded" });
  }

  function saveNote() {
    update({ agentNote: note });
    toast({ title: "Note saved" });
  }

  return (
    <div className="rounded-xl border bg-card p-4">
      <h3 className="mb-3 text-sm font-semibold text-foreground">Share with client</h3>
      <div className="space-y-2">
        <Button variant="default" size="sm" className="w-full justify-start" onClick={() => setShareOpen(true)}>
          <Send className="h-3.5 w-3.5" /> Send to Client
          {state.sentToClientAt && <span className="ml-auto text-[10px] opacity-80">Sent</span>}
        </Button>
        <Button variant="outline" size="sm" className="w-full justify-start" onClick={copyLink}>
          <LinkIcon className="h-3.5 w-3.5" /> Copy Client Link
        </Button>
        <Button variant="outline" size="sm" className="w-full justify-start" onClick={downloadOnePager}>
          <Download className="h-3.5 w-3.5" /> Download One-Page Summary
        </Button>
      </div>

      <div className="mt-4 border-t border-border pt-3">
        <label className="mb-1.5 flex items-center gap-1.5 text-xs font-medium text-foreground">
          <StickyNote className="h-3.5 w-3.5" /> Agent note
        </label>
        <Textarea
          value={note}
          onChange={(e) => setNote(e.target.value)}
          placeholder="Internal note (not shared with client)…"
          rows={3}
          className="text-sm"
        />
        <Button
          size="sm"
          variant="ghost"
          className="mt-2 w-full"
          onClick={saveNote}
          disabled={note === state.agentNote}
        >
          Save note
        </Button>
      </div>

      <Dialog open={shareOpen} onOpenChange={setShareOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Send to client?</DialogTitle>
            <DialogDescription>
              {rel.clientName ? (
                <>We'll share <strong>{rel.propertyName}</strong> with <strong>{rel.clientName}</strong> and notify them by email.</>
              ) : (
                <>We'll share <strong>{rel.propertyName}</strong> with your client and notify them by email.</>
              )}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShareOpen(false)}>Cancel</Button>
            <Button onClick={confirmSend}>Send</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}
