import { useState } from "react";
import {
  Send, ArrowRight, HelpCircle, XCircle, Sparkles, Bell, Handshake, MessageSquare, Phone, FileText, FileCheck, FileSignature, Archive, RotateCcw, Link as LinkIcon, Download, StickyNote,
} from "lucide-react";
import {
  Sheet, SheetContent, SheetHeader, SheetTitle, SheetDescription,
} from "@/components/ui/sheet";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import type { Relationship } from "@/features/matches/hooks/useUnifiedRelationships";
import { LifecycleTracker } from "./LifecycleTracker";
import { AgentCommsCard } from "./AgentCommsCard";
import { useMatchActions } from "./useMatchActions";
import { useMatchLocalState } from "./useMatchLocalState";
import { UI_STATUS_CLASS, UI_STATUS_LABEL } from "./inboxHelpers";

const ACTION_ICONS: Record<string, typeof Send> = {
  send_to_client: Send,
  request_seller_details: HelpCircle,
  not_a_fit: XCircle,
  mark_interested: Sparkles,
  follow_up_client: Bell,
  client_passed: XCircle,
  request_agent_intro: Handshake,
  send_client_questions: HelpCircle,
  open_conversation: MessageSquare,
  schedule_call: Phone,
  request_documents: FileText,
  start_reviewing_docs: FileCheck,
  mark_loi_sent: FileSignature,
  mark_under_contract: FileSignature,
  archive: Archive,
  reactivate: RotateCcw,
};

const STATUS_HINTS: Record<string, string> = {
  new: "Fresh match — share it with your client to gauge interest.",
  sent_to_client: "Waiting on your client. Nudge them or log their response.",
  client_interested: "Client is in. Request an intro to the listing agent.",
  agent_connected: "You're connected — keep the conversation moving.",
  reviewing_docs: "Diligence underway. Move to LOI when ready.",
  loi: "Offer on the table. Update once it goes under contract.",
  under_contract: "Under contract. Track to close in the conversation.",
  closed: "Deal closed. Nice work.",
  archived: "Archived. Reactivate to resume work on this match.",
};

interface Props {
  rel: Relationship;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

export function MatchWorkflowDrawer({ rel, open, onOpenChange }: Props) {
  const { toast } = useToast();
  const [shareOpen, setShareOpen] = useState(false);
  const { state, update } = useMatchLocalState(rel.matchId);
  const [note, setNote] = useState(state.agentNote);

  const { status, primary, secondary, handle, busy } = useMatchActions(rel, {
    onSendToClient: () => setShareOpen(true),
  });

  const shareUrl = `${window.location.origin}/share/match/${rel.matchId}`;
  const PrimaryIcon = primary ? ACTION_ICONS[primary.id] ?? ArrowRight : null;
  const constructive = secondary.filter((a) => a.tone !== "destructive");
  const destructive = secondary.filter((a) => a.tone === "destructive");

  function confirmSend() {
    update({ sentToClientAt: new Date().toISOString() });
    setShareOpen(false);
    toast({ title: "Sent to client", description: rel.clientName ? `Notified ${rel.clientName}.` : undefined });
  }

  function copyLink() {
    navigator.clipboard.writeText(shareUrl).then(
      () => toast({ title: "Link copied" }),
      () => toast({ title: "Copy failed", variant: "destructive" }),
    );
  }

  function downloadOnePager() {
    const lines = [
      `Property: ${rel.propertyName}`,
      `Location: ${[rel.propertyCity, rel.propertyState].filter(Boolean).join(", ") || "—"}`,
      `Match score: ${Math.round(rel.score)}/100`,
      "",
      "Generated by 1031ExchangeUp",
    ].join("\n");
    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${rel.propertyName.replace(/\s+/g, "_")}_one-pager.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "One-pager downloaded" });
  }

  function saveNote() {
    update({ agentNote: note });
    toast({ title: "Note saved" });
  }

  const activityEvents: Array<{ ts: string; label: string }> = [];
  activityEvents.push({ ts: rel.lastActivityAt, label: "Most recent activity" });
  if (rel.acceptedAt) activityEvents.push({ ts: rel.acceptedAt, label: "Connection accepted" });
  if (rel.underContractAt) activityEvents.push({ ts: rel.underContractAt, label: "Under contract" });
  if (rel.closedAt) activityEvents.push({ ts: rel.closedAt, label: "Deal closed" });
  activityEvents.push({ ts: rel.lastActivityAt, label: "Match created" });

  return (
    <>
      <Sheet open={open} onOpenChange={onOpenChange}>
        <SheetContent className="w-full overflow-y-auto p-0 sm:max-w-xl">
          <SheetHeader className="sticky top-0 z-10 border-b bg-card/95 px-6 py-4 backdrop-blur">
            <div className="flex items-center justify-between gap-3">
              <div className="min-w-0">
                <SheetTitle className="truncate text-base">Manage match</SheetTitle>
                <SheetDescription className="truncate text-xs">
                  {rel.propertyName}{rel.clientName ? ` · for ${rel.clientName}` : ""}
                </SheetDescription>
              </div>
              <span
                className={cn(
                  "inline-flex items-center rounded-full border px-2.5 py-0.5 text-[10px] font-semibold uppercase tracking-wide",
                  UI_STATUS_CLASS[status],
                )}
              >
                {UI_STATUS_LABEL[status]}
              </span>
            </div>
          </SheetHeader>

          <div className="space-y-6 p-6">
            {/* Action Center */}
            <section className="rounded-xl border bg-gradient-to-br from-primary/5 to-card p-4">
              <p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">
                Action Center
              </p>
              <p className="mt-1.5 text-sm text-foreground">{STATUS_HINTS[status] ?? "Keep this deal moving."}</p>

              {primary && (
                <Button
                  size="lg"
                  className="mt-4 h-11 w-full gap-2 text-sm font-semibold"
                  onClick={() => handle(primary.id, primary.label)}
                  disabled={busy === primary.id}
                >
                  {PrimaryIcon && <PrimaryIcon className="h-4 w-4" />}
                  {primary.label}
                  <ArrowRight className="h-4 w-4 opacity-70" />
                </Button>
              )}

              {(constructive.length > 0 || destructive.length > 0) && (
                <div className="mt-3 flex flex-wrap gap-1.5">
                  {constructive.map((a) => {
                    const Icon = ACTION_ICONS[a.id];
                    return (
                      <button
                        key={a.id}
                        type="button"
                        onClick={() => handle(a.id, a.label)}
                        disabled={busy === a.id}
                        className="inline-flex items-center gap-1.5 rounded-full border border-border bg-card px-3 py-1.5 text-xs font-medium text-foreground/80 hover:border-primary/40 hover:bg-primary/5 disabled:opacity-50"
                      >
                        {Icon && <Icon className="h-3.5 w-3.5" />}
                        {a.label}
                      </button>
                    );
                  })}
                  {destructive.map((a) => {
                    const Icon = ACTION_ICONS[a.id];
                    return (
                      <button
                        key={a.id}
                        type="button"
                        onClick={() => handle(a.id, a.label)}
                        disabled={busy === a.id}
                        className="inline-flex items-center gap-1.5 rounded-full px-3 py-1.5 text-xs font-medium text-destructive/80 hover:bg-destructive/10 hover:text-destructive disabled:opacity-50"
                      >
                        {Icon && <Icon className="h-3.5 w-3.5" />}
                        {a.label}
                      </button>
                    );
                  })}
                </div>
              )}
            </section>

            {/* Lifecycle */}
            <section>
              <LifecycleTracker status={status} variant="full" />
            </section>

            {/* Share with client */}
            <section className="rounded-xl border bg-card p-4">
              <h3 className="text-sm font-semibold text-foreground">Share with client</h3>
              <div className="mt-3 flex flex-wrap gap-2">
                <Button size="sm" onClick={() => setShareOpen(true)}>
                  <Send className="mr-1.5 h-3.5 w-3.5" /> Send to client
                  {state.sentToClientAt && <span className="ml-2 text-[10px] opacity-80">Sent</span>}
                </Button>
                <Button variant="outline" size="sm" onClick={copyLink}>
                  <LinkIcon className="mr-1.5 h-3.5 w-3.5" /> Copy link
                </Button>
                <Button variant="outline" size="sm" onClick={downloadOnePager}>
                  <Download className="mr-1.5 h-3.5 w-3.5" /> One-pager
                </Button>
              </div>
              <div className="mt-4">
                <label className="mb-1.5 flex items-center gap-1.5 text-xs font-medium text-foreground">
                  <StickyNote className="h-3.5 w-3.5" /> Internal note
                </label>
                <Textarea
                  value={note}
                  onChange={(e) => setNote(e.target.value)}
                  placeholder="Add context for yourself…"
                  rows={3}
                  className="text-sm"
                />
                <Button size="sm" variant="outline" className="mt-2" onClick={saveNote} disabled={note === state.agentNote}>
                  Save note
                </Button>
              </div>
            </section>

            {/* Conversation */}
            <section>
              <AgentCommsCard rel={rel} />
            </section>

            {/* Activity */}
            <section className="rounded-xl border bg-card p-4">
              <h3 className="mb-3 text-sm font-semibold text-foreground">Activity</h3>
              <ol className="relative space-y-3 border-l border-border pl-4">
                {activityEvents.map((e, i) => (
                  <li key={i} className="relative">
                    <span className="absolute -left-[21px] top-1.5 h-2 w-2 rounded-full bg-primary" />
                    <p className="text-sm font-medium text-foreground">{e.label}</p>
                    <p className="text-xs text-muted-foreground">{new Date(e.ts).toLocaleString()}</p>
                  </li>
                ))}
              </ol>
            </section>
          </div>
        </SheetContent>
      </Sheet>

      <Dialog open={shareOpen} onOpenChange={setShareOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Send to client?</DialogTitle>
            <DialogDescription>
              {rel.clientName ? (
                <>We'll share <strong>{rel.propertyName}</strong> with <strong>{rel.clientName}</strong> and notify them by email.</>
              ) : (
                <>We'll share <strong>{rel.propertyName}</strong> with your client and notify them by email.</>
              )}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShareOpen(false)}>Cancel</Button>
            <Button onClick={confirmSend}>Send</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </>
  );
}
