import { useState } from "react";
import { Link } from "react-router-dom";
import { MapPin, ExternalLink, FileText, Activity, Info, Send, Link as LinkIcon, Download, StickyNote } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from "@/components/ui/dialog";
import { useToast } from "@/hooks/use-toast";
import { cn } from "@/lib/utils";
import type { Relationship } from "@/features/matches/hooks/useUnifiedRelationships";
import { currency, scoreDotClass } from "../helpers";
import { WhyThisMatched } from "./WhyThisMatched";
import { MatchBreakdownChart } from "./MatchBreakdownChart";
import { AgentCommsCard } from "./AgentCommsCard";
import { LifecycleTracker } from "./LifecycleTracker";
import {
  financialMetrics,
  rankExplanation,
  UI_STATUS_CLASS,
  UI_STATUS_LABEL,
} from "./inboxHelpers";
import { useMatchActions } from "./useMatchActions";
import { useMatchLocalState } from "./useMatchLocalState";
import { propertyImage } from "./propertyImage";
import { getClientAccent } from "@/features/matches/lib/clientAccent";
import { ClientLeadLine } from "@/features/matches/components/shared/ClientLeadLine";

interface Props {
  rel: Relationship;
  rank?: number | null;
  totalInScope?: number;
}

const KEY_METRIC_KEYS = ["noi", "cap", "coc", "dscr", "occupancy", "equity", "loan", "cashflow"];

export function PropertyReviewPanel({ rel, rank, totalInScope }: Props) {
  const allMetrics = financialMetrics(rel);
  const keyMetrics = KEY_METRIC_KEYS
    .map((k) => allMetrics.find((m) => m.key === k))
    .filter(Boolean) as ReturnType<typeof financialMetrics>;

  const { status, primary, secondary, handle, busy } = useMatchActions(rel, {
    onSendToClient: () => setShareOpen(true),
  });

  const { state, update } = useMatchLocalState(rel.matchId);
  const { toast } = useToast();
  const [shareOpen, setShareOpen] = useState(false);
  const [note, setNote] = useState(state.agentNote);

  const shareUrl = `${window.location.origin}/share/match/${rel.matchId}`;

  function confirmSend() {
    update({ sentToClientAt: new Date().toISOString() });
    setShareOpen(false);
    toast({ title: "Sent to client", description: rel.clientName ? `Notified ${rel.clientName}.` : undefined });
  }

  function copyLink() {
    navigator.clipboard.writeText(shareUrl).then(
      () => toast({ title: "Link copied" }),
      () => toast({ title: "Copy failed", variant: "destructive" }),
    );
  }

  function downloadOnePager() {
    const lines = [
      `Property: ${rel.propertyName}`,
      `Location: ${[rel.propertyCity, rel.propertyState].filter(Boolean).join(", ") || "—"}`,
      `Match score: ${Math.round(rel.score)}/100`,
      "",
      "Financials",
      ...allMetrics.map((m) => `  ${m.label}: ${m.value}${m.estimated ? "  (est.)" : ""}`),
      "",
      "Generated by 1031ExchangeUp",
    ].join("\n");
    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${rel.propertyName.replace(/\s+/g, "_")}_one-pager.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "One-pager downloaded" });
  }

  function saveNote() {
    update({ agentNote: note });
    toast({ title: "Note saved" });
  }

  const accent = getClientAccent(rel.clientId);

  return (
    <div className="flex h-full min-h-0 w-full min-w-0 flex-col overflow-hidden rounded-xl border bg-card">
      <div className="min-h-0 flex-1 overflow-y-auto overscroll-contain">
        {/* Client identity strip */}
        <div
          className={cn(
            "flex flex-wrap items-center gap-2 border-b border-border border-l-[4px] px-5 py-2.5",
            accent.borderLeft,
            accent.soft,
          )}
        >
          <ClientLeadLine
            clientId={rel.clientId}
            clientName={rel.clientName}
            relinquishedLabel={rel.relinquishedLabel}
            size="md"
            pill
          />
          <span className="hidden text-xs text-muted-foreground sm:inline">
            Trading out — finding replacement property
          </span>
          <Button asChild variant="ghost" size="sm" className="ml-auto h-7 px-2 text-xs">
            <Link to={`/agent/workspace/${rel.buyerExchangeId}`}>
              Open workspace <ExternalLink className="ml-1 h-3 w-3" />
            </Link>
          </Button>
        </div>

        {/* Hero image */}
        <div className="relative h-56 w-full overflow-hidden bg-muted">
          <img
            src={propertyImage(rel.propertyImageUrl, rel.id)}
            alt=""
            className="h-full w-full object-cover"
          />
          <span
            className={cn(
              "absolute right-3 top-3 inline-flex max-w-[60%] items-center whitespace-nowrap rounded-full border bg-card/95 px-2.5 py-1 text-xs font-medium backdrop-blur",
              UI_STATUS_CLASS[status],
            )}
          >
            {UI_STATUS_LABEL[status]}
          </span>
        </div>

        {/* Header */}
        <div className="border-b border-border px-5 py-4">
          <div className="flex flex-wrap items-start justify-between gap-3">
            <div className="min-w-0 flex-1">
              <h2 className="truncate text-xl font-semibold text-foreground">
                {rel.propertyName}
              </h2>
              <p className="mt-0.5 flex items-center gap-1 truncate text-sm text-muted-foreground">
                <MapPin className="h-3.5 w-3.5 shrink-0" />
                <span className="truncate">
                  {[rel.propertyCity, rel.propertyState].filter(Boolean).join(", ") || "—"}
                </span>
              </p>
              {rank != null && totalInScope ? (
                <p className="mt-1 text-[11px] font-medium text-foreground/70">
                  <span className="rounded bg-muted px-1.5 py-0.5 font-bold">#{rank}</span>
                  <span className="ml-1.5">of {totalInScope} matches</span>
                </p>
              ) : null}
            </div>

            <div className="flex shrink-0 items-center gap-3">
              <div className="text-right">
                <p className="text-lg font-semibold leading-none text-foreground">
                  {currency(rel.askingPrice)}
                </p>
                {rel.capRate != null && (
                  <p className="mt-1 text-[11px] text-muted-foreground">
                    {rel.capRate.toFixed(2)}% cap
                  </p>
                )}
              </div>
              <div className="flex flex-col items-center">
                <span
                  className={cn(
                    "flex h-9 min-w-9 items-center justify-center rounded-full px-2 text-sm font-bold text-white",
                    scoreDotClass(rel.score),
                  )}
                >
                  {Math.round(rel.score)}
                </span>
                <span className="mt-0.5 text-[10px] text-muted-foreground">score</span>
              </div>
            </div>
          </div>

          {/* Inline action row — primary + all secondary actions */}
          <div className="mt-3 flex flex-wrap items-center gap-2">
            {primary ? (
              <Button
                size="sm"
                onClick={() => handle(primary.id, primary.label)}
                disabled={busy === primary.id}
              >
                {primary.label}
              </Button>
            ) : (
              <span className="text-xs text-muted-foreground">No further action required</span>
            )}
            {secondary.map((a) => (
              <Button
                key={a.id}
                variant={a.tone === "destructive" ? "ghost" : "outline"}
                size="sm"
                className={cn(
                  a.tone === "destructive" && "text-destructive hover:bg-destructive/10 hover:text-destructive",
                )}
                onClick={() => handle(a.id, a.label)}
                disabled={busy === a.id}
              >
                {a.label}
              </Button>
            ))}
            <Button asChild variant="ghost" size="sm" className="ml-auto">
              <Link to={`/agent/workspace/${rel.buyerExchangeId}?match=${rel.matchId}`}>
                Full details <ExternalLink className="ml-1 h-3 w-3" />
              </Link>
            </Button>
          </div>
        </div>

        {/* Lifecycle tracker */}
        <div className="border-b border-border px-5 py-3">
          <LifecycleTracker status={status} variant="compact" />
        </div>

        {/* Key metrics strip */}
        <div className="border-b border-border px-5 py-3">
          <h3 className="mb-2 text-xs font-semibold uppercase tracking-wide text-muted-foreground">
            Key metrics
          </h3>
          <div className="grid grid-cols-2 gap-2 sm:grid-cols-4 2xl:grid-cols-8">
            {keyMetrics.map((m) => (
              <div key={m.key} className="rounded-lg border bg-background px-2.5 py-2">
                <div className="flex items-center gap-1 text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
                  <span className="truncate">{m.label}</span>
                  {m.estimated && <Info className="h-2.5 w-2.5 shrink-0" aria-label="Estimated" />}
                </div>
                <p className="mt-0.5 truncate text-sm font-semibold text-foreground">{m.value}</p>
              </div>
            ))}
          </div>
        </div>

        {/* Why this matched + rank explanation */}
        <section className="space-y-4 border-b border-border px-5 py-5">
          <div>
            <h3 className="mb-2 text-sm font-semibold text-foreground">Why this matched</h3>
            {rank != null && (
              <div className="mb-3 rounded-lg border bg-primary/5 p-3 text-sm text-foreground/80">
                {rankExplanation(rel, rank)}
              </div>
            )}
            <WhyThisMatched rel={rel} />
          </div>
        </section>

        {/* Match breakdown */}
        <section className="border-b border-border px-5 py-5">
          <h3 className="mb-3 text-sm font-semibold text-foreground">Match breakdown</h3>
          <MatchBreakdownChart rel={rel} />
        </section>

        {/* Full financials */}
        <section className="border-b border-border px-5 py-5">
          <h3 className="mb-3 text-sm font-semibold text-foreground">Financials</h3>
          <FinancialGrid metrics={allMetrics} />
        </section>

        {/* Share with client */}
        <section className="border-b border-border px-5 py-5">
          <h3 className="mb-3 text-sm font-semibold text-foreground">Share with client</h3>
          <div className="flex flex-wrap gap-2">
            <Button size="sm" onClick={() => setShareOpen(true)}>
              <Send className="mr-1.5 h-3.5 w-3.5" /> Send to client
              {state.sentToClientAt && <span className="ml-2 text-[10px] opacity-80">Sent</span>}
            </Button>
            <Button variant="outline" size="sm" onClick={copyLink}>
              <LinkIcon className="mr-1.5 h-3.5 w-3.5" /> Copy client link
            </Button>
            <Button variant="outline" size="sm" onClick={downloadOnePager}>
              <Download className="mr-1.5 h-3.5 w-3.5" /> Download one-pager
            </Button>
          </div>
          <div className="mt-4">
            <label className="mb-1.5 flex items-center gap-1.5 text-xs font-medium text-foreground">
              <StickyNote className="h-3.5 w-3.5" /> Internal note (not shared with client)
            </label>
            <Textarea
              value={note}
              onChange={(e) => setNote(e.target.value)}
              placeholder="Add context for yourself…"
              rows={3}
              className="text-sm"
            />
            <Button
              size="sm"
              variant="outline"
              className="mt-2"
              onClick={saveNote}
              disabled={note === state.agentNote}
            >
              Save note
            </Button>
          </div>
        </section>

        {/* Conversation with counterparty agent */}
        <section className="border-b border-border px-5 py-5">
          <h3 className="mb-3 text-sm font-semibold text-foreground">Conversation</h3>
          <AgentCommsCard rel={rel} />
        </section>

        {/* Activity */}
        <section className="border-b border-border px-5 py-5">
          <h3 className="mb-3 text-sm font-semibold text-foreground">Activity</h3>
          <ActivityTimeline rel={rel} />
        </section>

        {/* Documents */}
        <section className="px-5 py-5">
          <h3 className="mb-3 text-sm font-semibold text-foreground">Documents</h3>
          <div className="flex flex-col items-center justify-center rounded-xl border border-dashed bg-muted/30 p-10 text-center">
            <FileText className="mb-3 h-10 w-10 text-muted-foreground/40" />
            <p className="text-sm font-medium text-foreground">No documents shared yet</p>
            <p className="mt-1 max-w-sm text-xs text-muted-foreground">
              Documents the other agent shares (OM, T-12, rent roll) will appear here.
            </p>
            <Button disabled size="sm" variant="outline" className="mt-4">
              Request documents
            </Button>
          </div>
        </section>
      </div>

      <Dialog open={shareOpen} onOpenChange={setShareOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Send to client?</DialogTitle>
            <DialogDescription>
              {rel.clientName ? (
                <>We'll share <strong>{rel.propertyName}</strong> with <strong>{rel.clientName}</strong> and notify them by email.</>
              ) : (
                <>We'll share <strong>{rel.propertyName}</strong> with your client and notify them by email.</>
              )}
            </DialogDescription>
          </DialogHeader>
          <DialogFooter>
            <Button variant="outline" onClick={() => setShareOpen(false)}>Cancel</Button>
            <Button onClick={confirmSend}>Send</Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  );
}

function FinancialGrid({ metrics }: { metrics: ReturnType<typeof financialMetrics> }) {
  return (
    <div className="grid grid-cols-2 gap-3 sm:grid-cols-3">
      {metrics.map((m) => (
        <div key={m.key} className="rounded-lg border bg-background p-3">
          <div className="flex items-center gap-1 text-[10px] font-medium uppercase tracking-wide text-muted-foreground">
            {m.label}
            {m.estimated && <Info className="h-3 w-3" aria-label="Estimated value" />}
          </div>
          <p className="mt-1 text-base font-semibold text-foreground">{m.value}</p>
        </div>
      ))}
    </div>
  );
}

function ActivityTimeline({ rel }: { rel: Relationship }) {
  const events: Array<{ ts: string; label: string }> = [];
  events.push({ ts: rel.lastActivityAt, label: "Most recent activity" });
  if (rel.acceptedAt) events.push({ ts: rel.acceptedAt, label: "Connection accepted" });
  if (rel.underContractAt) events.push({ ts: rel.underContractAt, label: "Under contract" });
  if (rel.closedAt) events.push({ ts: rel.closedAt, label: "Deal closed" });
  events.push({ ts: rel.lastActivityAt, label: "Match created" });

  return (
    <ol className="relative space-y-3 border-l border-border pl-4">
      {events.map((e, i) => (
        <li key={i} className="relative">
          <span className="absolute -left-[21px] top-1.5 h-2 w-2 rounded-full bg-primary" />
          <p className="text-sm font-medium text-foreground">{e.label}</p>
          <p className="text-xs text-muted-foreground">
            {new Date(e.ts).toLocaleString()}
          </p>
        </li>
      ))}
      {events.length === 1 && (
        <p className="pt-2 text-xs text-muted-foreground">
          <Activity className="mr-1 inline h-3 w-3" /> More activity will appear as the deal progresses.
        </p>
      )}
    </ol>
  );
}
