import { Link as LinkIcon, Download } from "lucide-react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import type { Relationship } from "@/features/matches/hooks/useUnifiedRelationships";
import { useMatchLocalState } from "./useMatchLocalState";

interface Props {
  rel: Relationship;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

/**
 * Confirmation dialog for sharing a matched property with the client.
 * Also hosts the lightweight share utilities (copy link, one-pager) so
 * they live where the agent is already thinking about sharing.
 */
export function SendToClientDialog({ rel, open, onOpenChange }: Props) {
  const { toast } = useToast();
  const { update } = useMatchLocalState(rel.matchId);

  const shareUrl = `${window.location.origin}/share/match/${rel.matchId}`;

  function confirmSend() {
    update({ sentToClientAt: new Date().toISOString() });
    onOpenChange(false);
    toast({
      title: "Sent to client",
      description: rel.clientName ? `Notified ${rel.clientName}.` : undefined,
    });
  }

  function copyLink() {
    navigator.clipboard.writeText(shareUrl).then(
      () => toast({ title: "Link copied" }),
      () => toast({ title: "Copy failed", variant: "destructive" }),
    );
  }

  function downloadOnePager() {
    const lines = [
      `Property: ${rel.propertyName}`,
      `Location: ${[rel.propertyCity, rel.propertyState].filter(Boolean).join(", ") || "—"}`,
      `Match score: ${Math.round(rel.score)}/100`,
      "",
      "Generated by 1031ExchangeUp",
    ].join("\n");
    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${rel.propertyName.replace(/\s+/g, "_")}_one-pager.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "One-pager downloaded" });
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Send to client?</DialogTitle>
          <DialogDescription>
            {rel.clientName ? (
              <>We'll share <strong>{rel.propertyName}</strong> with <strong>{rel.clientName}</strong> and notify them by email.</>
            ) : (
              <>We'll share <strong>{rel.propertyName}</strong> with your client and notify them by email.</>
            )}
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-wrap gap-2">
          <Button variant="outline" size="sm" onClick={copyLink}>
            <LinkIcon className="mr-1.5 h-3.5 w-3.5" /> Copy share link
          </Button>
          <Button variant="outline" size="sm" onClick={downloadOnePager}>
            <Download className="mr-1.5 h-3.5 w-3.5" /> Download one-pager
          </Button>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button onClick={confirmSend}>Send</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
