import { Download } from "lucide-react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import type { Relationship } from "@/features/matches/hooks/useUnifiedRelationships";
import { useMatchLocalState } from "./useMatchLocalState";

interface Props {
  rel: Relationship;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

/**
 * Confirmation dialog for marking a matched property as shared with the client.
 * Sharing happens out-of-band (the agent sends the one-pager however they like);
 * this records it and advances the match to "Sent to Client" in the pipeline.
 */
export function SendToClientDialog({ rel, open, onOpenChange }: Props) {
  const { toast } = useToast();
  const { update } = useMatchLocalState(rel.matchId);

  function confirmSend() {
    update({ sentToClientAt: new Date().toISOString() });
    onOpenChange(false);
    toast({
      title: "Marked as sent to client",
      description: "Moved to “Sent to Client” in your pipeline.",
    });
  }

  function downloadOnePager() {
    const lines = [
      `Property: ${rel.propertyName}`,
      `Location: ${[rel.propertyCity, rel.propertyState].filter(Boolean).join(", ") || "—"}`,
      `Match score: ${Math.round(rel.score)}/100`,
      "",
      "Generated by 1031ExchangeUp",
    ].join("\n");
    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${rel.propertyName.replace(/\s+/g, "_")}_one-pager.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "One-pager downloaded" });
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Send to client?</DialogTitle>
          <DialogDescription>
            {rel.clientName ? (
              <>This marks <strong>{rel.propertyName}</strong> as shared with <strong>{rel.clientName}</strong> and moves it to <strong>Sent to Client</strong> in your pipeline. Download the one-pager below to send them directly.</>
            ) : (
              <>This marks <strong>{rel.propertyName}</strong> as shared with your client and moves it to <strong>Sent to Client</strong> in your pipeline. Download the one-pager below to send them directly.</>
            )}
          </DialogDescription>
        </DialogHeader>

        <div className="flex flex-wrap gap-2">
          <Button variant="outline" size="sm" onClick={downloadOnePager}>
            <Download className="mr-1.5 h-3.5 w-3.5" /> Download one-pager
          </Button>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button onClick={confirmSend}>Mark as sent</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
