import { useState } from "react";
import { Download } from "lucide-react";
import {
  Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter,
} from "@/components/ui/dialog";
import { Button } from "@/components/ui/button";
import { useToast } from "@/hooks/use-toast";
import type { Relationship } from "@/features/matches/hooks/useUnifiedRelationships";
import { useMatchLocalState } from "./useMatchLocalState";
import { supabase } from "@/integrations/supabase/client";
import { Textarea } from "@/components/ui/textarea";

interface Props {
  rel: Relationship;
  open: boolean;
  onOpenChange: (open: boolean) => void;
}

/**
 * Confirmation dialog for marking a matched property as shared with the client.
 * Sharing happens out-of-band (the agent sends the one-pager however they like);
 * this records it and advances the match to "Sent to Client" in the pipeline.
 */
export function SendToClientDialog({ rel, open, onOpenChange }: Props) {
  const { toast } = useToast();
  const { update } = useMatchLocalState(rel.matchId);
  const [note, setNote] = useState("");
  const [sending, setSending] = useState(false);

  async function confirmSend() {
    setSending(true);
    const { error } = await supabase.rpc("recommend_match_to_client" as any, {
      p_match_id: rel.matchId,
      p_note: note.trim() || null,
    });
    setSending(false);
    if (error) {
      toast({ title: "Couldn't recommend this match", description: error.message, variant: "destructive" });
      return;
    }
    update({ sentToClientAt: new Date().toISOString() });
    onOpenChange(false);
    setNote("");
    toast({
      title: "Recommendation sent",
      description: "Your client can review it in their investor workspace.",
    });
  }

  function downloadOnePager() {
    const lines = [
      `Property: ${rel.propertyName}`,
      `Location: ${[rel.propertyCity, rel.propertyState].filter(Boolean).join(", ") || "—"}`,
      `Match score: ${Math.round(rel.score)}/100`,
      "",
      "Generated by 1031ExchangeUp",
    ].join("\n");
    const blob = new Blob([lines], { type: "text/plain" });
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = `${rel.propertyName.replace(/\s+/g, "_")}_one-pager.txt`;
    a.click();
    URL.revokeObjectURL(url);
    toast({ title: "One-pager downloaded" });
  }

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent>
        <DialogHeader>
          <DialogTitle>Recommend this match?</DialogTitle>
          <DialogDescription>
            {rel.clientName ? (
              <>Send <strong>{rel.propertyName}</strong> to <strong>{rel.clientName}</strong>'s investor workspace. Their response will return to your action queue.</>
            ) : (
              <>Send <strong>{rel.propertyName}</strong> to your client's investor workspace. They must have accepted their client invitation first.</>
            )}
          </DialogDescription>
        </DialogHeader>

        <Textarea value={note} onChange={(event) => setNote(event.target.value)} placeholder="Why you think this could fit their exchange (optional)" rows={3} />

        <div className="flex flex-wrap gap-2">
          <Button variant="outline" size="sm" onClick={downloadOnePager}>
            <Download className="mr-1.5 h-3.5 w-3.5" /> Download one-pager
          </Button>
        </div>

        <DialogFooter>
          <Button variant="outline" onClick={() => onOpenChange(false)}>Cancel</Button>
          <Button onClick={confirmSend} disabled={sending}>{sending ? "Sending…" : "Recommend to client"}</Button>
        </DialogFooter>
      </DialogContent>
    </Dialog>
  );
}
