import { useState } from "react";
import { Mail, MessageCircle, Phone } from "lucide-react";
import { toast } from "sonner";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Textarea } from "@/components/ui/textarea";
import { useAgentInvestorInquiries } from "@/features/investor/hooks/useInvestorInquiries";
import { investorErrorMessage } from "@/features/investor/errorMessage";

export default function AgentInvestorInquiries() {
  const { data: inquiries = [], isLoading, respond } = useAgentInvestorInquiries();
  const [responses, setResponses] = useState<Record<string, string>>({});
  const submit = async (id: string) => { const response = responses[id]?.trim(); if (!response) return; try { await respond.mutateAsync({ inquiryId: id, response }); toast.success("Response sent to the investor."); } catch (error: unknown) { toast.error(investorErrorMessage(error, "Could not send response.")); } };
  return <div className="space-y-6"><div><h1 className="text-2xl font-bold">Investor leads</h1><p className="mt-1 text-sm text-muted-foreground">Questions from investors interested in properties you represent.</p></div>{isLoading ? <div className="py-20 text-center">Loading…</div> : inquiries.length ? <div className="space-y-4">{inquiries.map((inquiry) => <Card key={inquiry.id}><CardHeader><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-lg">{inquiry.propertyName}</CardTitle><p className="mt-1 text-sm text-muted-foreground">From {inquiry.investorName || "Investor"}{inquiry.propertyLocation ? ` · ${inquiry.propertyLocation}` : ""}</p></div><Badge variant={inquiry.status === "new" ? "default" : "secondary"}>{inquiry.status}</Badge></div></CardHeader><CardContent className="space-y-4"><div className="flex flex-wrap gap-4 text-sm">{inquiry.investorEmail && <a className="flex items-center gap-1 text-[#16284a] underline" href={`mailto:${inquiry.investorEmail}`}><Mail className="h-4 w-4" />{inquiry.investorEmail}</a>}{inquiry.investorPhone && <a className="flex items-center gap-1 text-[#16284a] underline" href={`tel:${inquiry.investorPhone}`}><Phone className="h-4 w-4" />{inquiry.investorPhone}</a>}</div><div className="rounded-lg bg-muted/60 p-4 text-sm">{inquiry.initialMessage}</div>{inquiry.agentResponse ? <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-semibold uppercase text-emerald-700">Your response</p><p className="mt-2 text-sm">{inquiry.agentResponse}</p></div> : <div className="space-y-2"><Textarea aria-label={`Response to ${inquiry.investorName || "investor"}`} rows={4} placeholder="Write a helpful response…" value={responses[inquiry.id] ?? ""} onChange={(e) => setResponses((current) => ({ ...current, [inquiry.id]: e.target.value }))} /><Button onClick={() => submit(inquiry.id)} disabled={!responses[inquiry.id]?.trim() || respond.isPending}>Send response</Button></div>}</CardContent></Card>)}</div> : <div className="rounded-xl border border-dashed p-12 text-center"><MessageCircle className="mx-auto h-10 w-10 text-muted-foreground/40" /><p className="mt-3 font-semibold">No investor inquiries</p><p className="mt-1 text-sm text-muted-foreground">New property inquiries will appear here.</p></div>}</div>;
}
