import { Link } from "react-router-dom";
import { MessageCircle } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { useInvestorInquiries } from "@/features/investor/hooks/useInvestorInquiries";

export default function InvestorInquiries() {
  const { data: inquiries = [], isLoading } = useInvestorInquiries();
  return <div className="space-y-6"><div><h1 className="text-3xl font-bold tracking-tight text-[#16284a]">Property inquiries</h1><p className="mt-2 text-muted-foreground">Track questions sent to listing agents and their responses.</p></div>{isLoading ? <div className="py-20 text-center">Loading…</div> : inquiries.length ? <div className="space-y-4">{inquiries.map((inquiry) => <Card key={inquiry.id}><CardHeader className="pb-3"><div className="flex flex-wrap items-start justify-between gap-3"><div><CardTitle className="text-lg">{inquiry.propertyName}</CardTitle>{inquiry.propertyLocation && <p className="mt-1 text-sm text-muted-foreground">{inquiry.propertyLocation}</p>}</div><Badge variant={inquiry.status === "responded" ? "default" : "secondary"}>{inquiry.status === "responded" ? "Agent responded" : inquiry.status}</Badge></div></CardHeader><CardContent className="space-y-4"><div className="rounded-lg bg-slate-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-muted-foreground">Your message</p><p className="mt-2 text-sm">{inquiry.initialMessage}</p></div>{inquiry.agentResponse && <div className="rounded-lg border border-emerald-200 bg-emerald-50 p-4"><p className="text-xs font-semibold uppercase tracking-wide text-emerald-700">Listing agent response</p><p className="mt-2 text-sm text-emerald-950">{inquiry.agentResponse}</p></div>}<div className="flex items-center justify-between text-xs text-muted-foreground"><span>Sent {new Date(inquiry.createdAt).toLocaleDateString()}</span><Button asChild size="sm" variant="outline"><Link to={`/investor/properties/${inquiry.propertyId}`}>View property</Link></Button></div></CardContent></Card>)}</div> : <div className="rounded-xl border border-dashed bg-white p-12 text-center"><MessageCircle className="mx-auto h-10 w-10 text-slate-300" /><p className="mt-3 font-semibold">No inquiries yet</p><p className="mt-1 text-sm text-muted-foreground">Open a property and contact its listing agent when you want more information.</p></div>}</div>;
}
